version: '3.8'

services:
  app:
    image: "lnd-web-api2:latest"
    build:
      context: ..
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: myuserpassword
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readinessState || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - my-bridge-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: myuserpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myusername -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge